DEFAULT_APP_DEFAULT_ALGO      = 'Blowfish'
DEFAULT_APP_USE_DEFAULT_ALGO  = True
DEFAULT_TEXT_BASE_C           = '#fdf6e3'
DEFAULT_TEXT_TEXT_C           = '#586e75'
DEFAULT_TEXT_HIGHLIGHT_C      = '#586e75'
DEFAULT_TEXT_HIGHLIGHTTEXT_C  = '#fdf6e3'
DEFAULT_TEXT_LINENUMBER_C     = '#93a1a1'
DEFAULT_TEXT_LINENUMBERBG_C   = '#eee8d5'
DEFAULT_TEXT_FONTFAMILY       = 'Courier New'
DEFAULT_TEXT_FONTSIZE         = 10

OK             = 0
NOT_TEXT       = 1
NOT_SUPPORTED  = 2
INTERNAL_ERROR = 3
NOT_AVAILABLE  = 4